language: node_js
node_js:
  - "0.12.4"
sudo: required
before_install:
  - npm install -g grunt-cli bower
  - sudo apt-get install nsis
script:
  - grunt clean:releases
  - grunt build
  - grunt compress
